feat: users/guimatheus92/v0.5.0
shmuelzon/home-assistant-floor-plan pull request #40
Opened 2024-07-05 13:13 UTC by guimatheus92

I have added a couple of features and improved the documentation.

What I have added:

- Plugin will not open until user has opened a project on SH3D, that way we can prevent errors and streamlining the user workflow:

![image](https://github.com/shmuelzon/home-assistant-floor-plan/assets/11640754/ba1d2762-03ef-4d29-ab57-b7a98bc19b41)

- User can now choose betwen `HIGH` and `LOW` quality before exporting his images:
![image](https://github.com/shmuelzon/home-assistant-floor-plan/assets/11640754/cd022fc5-44a1-4460-97bc-2d3e2016ae54)

- The`Title` key-value from `.yaml` file can now be filled by user in SH3D in the `description` field in user project. That way, everytime a new file is generated, the data will be there saved in his project:

SH3D:

![image](https://github.com/shmuelzon/home-assistant-floor-plan/assets/11640754/a14a54d4-8dcf-4612-aa63-7ddbf7b2055c)

YAML:

``` yaml
  - type: state-icon
    entity: switch.kitchen_4
    title: Light Kitchen
    style:
      top: 70.37%
      left: 65.07%
      border-radius: 50%
      text-align: center
      background-color: rgba(255, 255, 255, 0.3)
    tap_action:
      action: toggle
```

- Since I am using Windows, the Makefile didn't work for me. So I created a PowerShell file following the same logic (great solution btw) that do the same work. 

**For Windows only**: I wasn't able to download the SweetHome3D `.jar` file using this method, so I have commented that line. For now, I suggest to download manually and place under a folder called `dl`

2024-07-05 13:19 UTC, guimatheus92 commented
@shmuelzon I don't if is possible to Pull Request my tag and my release as well, I wasn't able to do that. Or, if I should drag the file in here manually.

2024-07-06 07:30 UTC, shmuelzon requested changes

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +  - Use existing exported renders to process quicker than the first time
```suggestion
  - Caches previously rendered images to save time when generating the next floorplan
```

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +# How to activate plugin:
```suggestion
# How To Use The Plugin
```

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +1. Download the latest release in `.jar` and copy to Sweet Home 3D "plugins" folder (see notes below) or download the latest release in `.sh3p` and execute that file.
There are no `jar` files in the releases, only an `sh3p` file

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +> 	If double-clicking on a `.sh3p` file doesn't launch Sweet Home 3D (most chances under Linux), you can also install a plug-in with the following command in a Terminal window (where SweetHome3D is t
Please try to limit each line here (and in this file in general) to 80 characters

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +3. Go to `Tools` in Sweet Home 3D -> Home Assistant Lightning Export
```suggestion
3. Go to `Tools` in Sweet Home 3D -> Home Assistant Floor Plan
```

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +4. Move the generated images from Path to `/config/www/planes`
```suggestion
4. Copy the `floorplan` directory with all the images in it to your Home Assistant configuration directory `/config/www/`
```

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +5. Create a card of type `picture-elements` and paste the generated `.yaml` from Path.
```suggestion
5. Create a card of type `picture-elements` and paste the contents of the generated `floorplan.yaml`  
```

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +# How to activate plugin:
Why do we need this entire section? It already exists under `Usage`

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +  After the process is complete, copy the floorplan folder and floorplan.yaml to your Home Assistant path, specifically to: \config\www.
```suggestion
  After the process is complete, copy the floorplan folder and floorplan.yaml to your Home Assistant path, specifically to: /config/www.
```

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +  Prior to activating the plugin, go to “Create photo…” in the SH3D project and adjust the settings there. You do not need to render or save anything; simply make the changes and close the dialog.
```suggestion
  Prior to activating the plugin, go to "Create photo…" in the SH3D project and adjust the settings there. You do not need to render or save anything; simply make the changes and close the dialog.
```

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +## Contribute
I think this section should go in a separate `CONTRIBUTING.md` file

2024-07-06 07:30 UTC, shmuelzon commented on README.md
> +If you are using a UNIX system, just run the `Makefile` and it will generate the necessary build to run this plugin.
```suggestion
If you are using a UNIX system, just run `make` to build the plugin. `make test` will install the plugin and start SH3D.
```

2024-07-06 07:30 UTC, shmuelzon commented on build.ps1
> +param (
I'm sorry, but I would rather not maintain two different build scripts.
I'm also on Windows and just use WSL to build the plugin

2024-07-06 07:30 UTC, shmuelzon commented on src/com/shmuelzon/HomeAssistantFloorPlan/Controller.java
> +    public Home getHome() {
I'd rather not expose `Home` directly to the UI. If you really want to indicate the project is empty, create a function specifically for that

2024-07-06 07:30 UTC, shmuelzon commented on src/com/shmuelzon/HomeAssistantFloorPlan/Controller.java
> +            "    title: %s\n" +
If the description is empty, what will appear here (and in the HA frontend)? Will the behavior remain the same?

2024-07-06 07:30 UTC, shmuelzon commented on src/com/shmuelzon/HomeAssistantFloorPlan/Controller.java
> +            stateIcons.add(new StateIcon(lightsList.get(0).getName(), lightsCenter, "icon", "toggle", lightsList.get(0).getDescription() != null ? lightsList.get(0).getDescription() : lightsList.get(
I think I prefer the title to remain null and not have a tooltip with the name of the entity

2024-07-06 07:30 UTC, shmuelzon commented on src/com/shmuelzon/HomeAssistantFloorPlan/Controller.java
> +            String title = piece.getDescription() != null ? piece.getDescription() : piece.getName();
Same

2024-07-06 07:30 UTC, shmuelzon commented on src/com/shmuelzon/HomeAssistantFloorPlan/Panel.java
> +import java.awt.*;
I prefer explicit imports and not wildcards

2024-07-06 07:31 UTC, shmuelzon commented
Thank you for the pull request!
Would it be possible to split each feature/change to a separate pull request?
That way it'll show up properly in the change log.

Thanks!

2024-07-06 11:04 UTC, guimatheus92 commented
> Thank you for the pull request!
> 
> Would it be possible to split each feature/change to a separate pull request?
> 
> That way it'll show up properly in the change log.
> 
> 
> 
> Thanks!

Sure, I will take some time do undo all I did and create a PR for each but I will do. There a couple of comments there that I don't know how to solve, so I might open an issue to ask help/ideas so I can implement.

2024-07-06 21:28 UTC, closed without merging